microservices:
  {{cookiecutter.docker_image_name}}:
    build:
      env: '{%- if cookiecutter.build_system == 'gradle' %}gradlew{%- else %}mvnw{%- endif %}'
      path: '.'
      args: 'clean {%- if cookiecutter.build_system == 'gradle' %}build{%- else %}package{%- endif %}'
    docker:
      dockerfile: './Dockerfile'
      customTags:
        - 'latest'
      cacheFromTag: 'latest'
    chartPath: '{{cookiecutter.k8s_values_first_level}}.{{cookiecutter.k8s_values_second_level}}.image'
charts:
  - '{{cookiecutter.helm_chart_name}}'
