apiVersion: v1
kind: Service
metadata:
  name: {% raw %}{{{% endraw %} include "{{cookiecutter.helm_chart_name}}.fullname" . {% raw %}}}{% endraw %}
  labels:
{% raw %}{{{% endraw %} include "{{cookiecutter.helm_chart_name}}.labels" . | indent 4 {% raw %}}}{% endraw %}
spec:
  ports:
    {% raw %}{{{% endraw %}- with .Values.{{cookiecutter.k8s_values_first_level}}.{{cookiecutter.k8s_values_second_level}}.service {% raw %}}}{% endraw %}
    - port: {% raw %}{{{% endraw %} .externalPort {% raw %}}}{% endraw %}
      targetPort: {% raw %}{{{% endraw %} .internalPort {% raw %}}}{% endraw %}
      protocol: TCP
      name: http
    {% raw %}{{{% endraw %}- end{% raw %}}}{% endraw %}
  selector:
    app.kubernetes.io/name: {% raw %}{{{% endraw %} include "{{cookiecutter.helm_chart_name}}.name" . {% raw %}}}{% endraw %}
    app.kubernetes.io/instance: {% raw %}{{{% endraw %} .Release.Name {% raw %}}}{% endraw %}
